# Generated by Django 3.2.9 on 2021-11-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='choice', to='polls.question'),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='choices',
            field=models.ManyToManyField(to='polls.Choice'),
        ),
    ]
